-- MySQL Script generated by MySQL Workbench
-- Sun May  8 16:16:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vendasbanco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vendasbanco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vendasbanco` DEFAULT CHARACTER SET utf8 ;
USE `vendasbanco` ;

-- -----------------------------------------------------
-- Table `vendasbanco`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendasbanco`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendasbanco`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendasbanco`.`produtos` (
  `cod` INT NOT NULL AUTO_INCREMENT,
  `id_categoria` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `preco` DECIMAL(20,2) NOT NULL,
  `qtd_estoque` INT NOT NULL,
  `unidade_medida` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`cod`),
  INDEX `fk_produtos_categoria_idx` (`id_categoria` ASC),
  CONSTRAINT `fk_produtos_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `vendasbanco`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendasbanco`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendasbanco`.`cliente` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `endereco` VARCHAR(150) NOT NULL,
  `telefone` VARCHAR(100) NOT NULL,
  `limite_credito` DECIMAL(20,2) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `cpf` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendasbanco`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendasbanco`.`vendedor` (
  `cod` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  `telefone` VARCHAR(100) NOT NULL,
  `porc_comissao` DECIMAL(20,2) NOT NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendasbanco`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendasbanco`.`vendas` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `id_vendedor` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `data` DATE NOT NULL,
  `prazo_pagto` VARCHAR(100) NOT NULL,
  `cond_pagto` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_vendas_cliente1_idx` (`id_cliente` ASC),
  INDEX `fk_vendas_vendedor1_idx` (`id_vendedor` ASC),
  CONSTRAINT `fk_vendas_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `vendasbanco`.`cliente` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendas_vendedor1`
    FOREIGN KEY (`id_vendedor`)
    REFERENCES `vendasbanco`.`vendedor` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendasbanco`.`intens_vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendasbanco`.`intens_vendas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_produto` INT NOT NULL,
  `id_venda` INT NOT NULL,
  `quant_vendida` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_intens_vendas_produtos1_idx` (`id_produto` ASC),
  INDEX `fk_intens_vendas_vendas1_idx` (`id_venda` ASC),
  CONSTRAINT `fk_intens_vendas_produtos1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `vendasbanco`.`produtos` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_intens_vendas_vendas1`
    FOREIGN KEY (`id_venda`)
    REFERENCES `vendasbanco`.`vendas` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
